#
# Makefile for the lgnas micom emulation drivers.
#
obj-$(CONFIG_LGNAS_HAS_NO_MCU)               += lgnas_n4b2_setup.o lgnas_n4b2_front.o lgnas_n4b2_timer.o \
                       lgnas_n4b2_lcd.o lgnas_n4b2_int_btn.o
